---
title: "p8105_hw6_mw3845"
author: "Minghe Wang"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(purrr)
```

# Problem 1

# Problem 2

```{r Problem2_clean_data}
homicide_df = read.csv("./data/homicide-data.csv")

homicide_df <- homicide_df %>% 
  mutate(
    city_state = paste(city, state, sep = ", "),
    solved_case = case_when(
      disposition %in% c("Closed without arrest", "Open/No arrest") ~ 0,
      disposition == "Closed by arrest" ~ 1
    )
  ) %>% 
  filter(
    !(city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL")) &
    victim_race %in% c("White", "Black")
  ) %>% 
  mutate(
    victim_age = ifelse(victim_age == "Unknown", NA, victim_age),
    victim_age = as.numeric(as.character(victim_age))
  )
```

After loading and cleaning data, the dataset `homicide_df` contains `r nrow(homicide_df)` rows and `r ncol(homicide_df)` columns. Key variables includes `victim_age`, `victim_race`, `city_state`, `solved_case`, etc. The variables will be used for model fitting for each city.

```{r Problem2_baltimore_result}
baltimore_df = homicide_df %>% 
  filter(city_state == "Baltimore, MD") %>% 
  select(solved_case, victim_age, victim_race, victim_sex)

baltimore_glm = 
  baltimore_df |> 
  glm(solved_case ~ victim_age + victim_race + victim_sex, data = _, family = binomial())

baltimore_glm |> 
  broom::tidy(
    exponentiate = TRUE,
    conf.int = TRUE
  ) |> 
  filter(term == "victim_sexMale") |>
  select(term, estimate, conf.low, conf.high, p.value) |> 
  knitr::kable(digits = 4)
```

